Ruby_ontap/BT1/blog/config/routes.rb
Rails.application.routes.draw do
  devise_for :logins
  resources :users
  root to: "users#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

Ruby_ontap/BT1/blog/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

Ruby_ontap/BT1/blog/app/models/login.rb
class Login < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

Ruby_ontap/BT1/blog/app/models/user.rb
class User < ApplicationRecord
    validates :password, length:{minimum: 4}
end

Ruby_ontap/BT1/blog/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticated_user!
end

Ruby_ontap/BT1/blog/app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
  end
end

Ruby_ontap/BT1/blog/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to user_url(@user), notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to user_url(@user), notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:name, :email, :password)
    end
end

Ruby_ontap/BT1/blog/app/helpers/application_helper.rb
module ApplicationHelper
end

Ruby_ontap/BT1/blog/app/helpers/articles_helper.rb
module ArticlesHelper
end

Ruby_ontap/BT1/blog/app/helpers/users_helper.rb
module UsersHelper
end

Ruby_ontap/BT1/blog/app/views/articles/index.html.erb
<h1>Articles#index</h1>
<p>Find me in app/views/articles/index.html.erb</p>

Ruby_ontap/BT1/blog/app/views/layouts/_footer.html.erb
<footer class="bg-light text-dark">
      <div class="container" >
            <div class="row">
                  <div class="col">
                        <h3>MDN</h3>
                        <ul>
                              <li>About</li>
                              <li>Hacks Blog</li>
                              <li>Careers</li>
                        </ul>
                  </div>
                  <div class="col">
                        <h3>Support</h3>
                        <ul>
                              <li>About</li>
                              <li>Hacks Blog</li>
                              <li>Careers</li>
                        </ul>
                  </div>
                  <div class="col">
                        <h3>Our communities</h3>
                        <ul>
                              <li>About</li>
                              <li>Hacks Blog</li>
                              <li>Careers</li>
                        </ul>
                  </div>
                  <div class="col">
                        <h3>Developers</h3>
                        <ul>
                              <li>About</li>
                              <li>Hacks Blog</li>
                              <li>Careers</li>
                        </ul>
                  </div>
            </div>
      </div>
</footer>

Ruby_ontap/BT1/blog/app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <%= link_to "My Blog", root_path, class:'navbar-brand' %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to "Home", root_path, class:'nav-link active' %>
        </li>

        <li class="nav-item">
          <%= link_to "Users", users_path, class:'nav-link' %>
        </li>
      </ul>
      <ul class="navbar-nav">
         <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            User
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="#">Action</a></li>
            <li><a class="dropdown-item" href="#">Another action</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li>
      </ul>
    </div>
  </div>
</nav>

Ruby_ontap/BT1/blog/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Project</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <%= render 'layouts/header' %>  
    <p class="notice"> <%= notice %></p>
    <p class="alert"> <%= alert %></p>
    <div class="container">
      <%= yield %>
    </div>
  </body>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
</html>

Ruby_ontap/BT1/blog/app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
<div class="row">
  <div class="col-lg-4 col-md-6 col-sm-12">
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div class="col-lg-4 col-md-6 col-sm-12">
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email %>
  </div>

  <div class="col-lg-4 col-md-6 col-sm-12">
    <%= form.label :password, style: "display: block" %>
    <%= form.text_field :password %>
  </div>

  <div class="col-lg-3 col-md-6 col-sm-12">
    <%= form.submit class:"btn-btn-primary", style: "margin-top:20px " %>
  </div>
  
</div>
<% end %>

Ruby_ontap/BT1/blog/app/views/users/_user.html.erb
<div id="<%= dom_id user %>">
  <p>
    <strong>Name:</strong>
    <%= user.name %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= user.email %>
  </p>

  <p>
    <strong>Password:</strong>
    <%= user.password %>
  </p>

</div>

Ruby_ontap/BT1/blog/app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Show this user", @user %> |
  <%= link_to "Back to users", users_path %>
</div>

Ruby_ontap/BT1/blog/app/views/users/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Users</h1>

<div id="users">

  <table class="table table-striped">
  <thead>
    <tr class="table-primary">
      <th scope="col">#</th>
      <th scope="col">Name</th>
      <th scope="col">Email</th>
      <th scope="col">Password</th>
      <th scope="col">Action</th>

    </tr>
  </thead>
  <tbody>
     <% @users.each do |user| %>
      <tr>
        <th scope="row">1</th>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= user.password %></td>
        <td><%= link_to "Show", user %></td>
      </tr>
    <% end %>
  </tbody>
</table>

</div>
<button class="btn btn-light">
 <%= link_to "New user", new_user_path %>
</button>

Ruby_ontap/BT1/blog/app/views/users/new.html.erb
<h1>New user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <button class="btn btn-secondary">
  <%= link_to "Back to users", users_path, style:"color:black; texdeconary:none" %>
  </button>
</div>

Ruby_ontap/BT1/blog/app/views/users/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @user %>

<div>
  <%= link_to "Edit this user", edit_user_path(@user) %> |
  <%= link_to "Back to users", users_path %>

  <%= button_to "Destroy this user", @user, method: :delete %>
</div>