RuBy_on_rail/Tuan9/project_rails-ruby/config/routes.rb
Rails.application.routes.draw do
  resources :books
  root "pages#home"
  resources :friends
  resources :books

  get 'about', to: 'pages#about'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Defines the root path route ("/")
  get 'pages/home'
end

RuBy_on_rail/Tuan9/project_rails-ruby/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

RuBy_on_rail/Tuan9/project_rails-ruby/app/models/book.rb
class Book < ApplicationRecord
end

RuBy_on_rail/Tuan9/project_rails-ruby/app/models/friend.rb
class Friend < ApplicationRecord
end

RuBy_on_rail/Tuan9/project_rails-ruby/app/models/quanly.rb
class Quanly < ApplicationRecord
end

RuBy_on_rail/Tuan9/project_rails-ruby/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

RuBy_on_rail/Tuan9/project_rails-ruby/app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: %i[ show edit update destroy ]

  # GET /books or /books.json
  def index
    @books = Book.all
  end

  # GET /books/1 or /books/1.json
  def show
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books or /books.json
  def create
    @book = Book.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to book_url(@book), notice: "Book was successfully created." }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1 or /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to book_url(@book), notice: "Book was successfully updated." }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1 or /books/1.json
  def destroy
    @book.destroy

    respond_to do |format|
      format.html { redirect_to books_url, notice: "Book was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def book_params
      params.require(:book).permit(:mahs_236, :hoten_236, :lop_236, :manganh_236, :tensach_236, :tentacgia_236, :soBM_236, :ngaymuon_236, :ngaytra_236, :ghichu_236)
    end
end

RuBy_on_rail/Tuan9/project_rails-ruby/app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  before_action :set_friend, only: %i[ show edit update destroy ]

  # GET /friends or /friends.json
  def index
    @friends = Friend.all
  end

  # GET /friends/1 or /friends/1.json
  def show
  end

  # GET /friends/new
  def new
    @friend = Friend.new
  end

  # GET /friends/1/edit
  def edit
  end

  # POST /friends or /friends.json
  def create
    @friend = Friend.new(friend_params)

    respond_to do |format|
      if @friend.save
        format.html { redirect_to friend_url(@friend), notice: "Friend was successfully created." }
        format.json { render :show, status: :created, location: @friend }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /friends/1 or /friends/1.json
  def update
    respond_to do |format|
      if @friend.update(friend_params)
        format.html { redirect_to friend_url(@friend), notice: "Friend was successfully updated." }
        format.json { render :show, status: :ok, location: @friend }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /friends/1 or /friends/1.json
  def destroy
    @friend.destroy

    respond_to do |format|
      format.html { redirect_to friends_url, notice: "Friend was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_friend
      @friend = Friend.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def friend_params
      params.require(:friend).permit(:first_name, :last_name, :phone, :twiter)
    end
end

RuBy_on_rail/Tuan9/project_rails-ruby/app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end
end

RuBy_on_rail/Tuan9/project_rails-ruby/app/controllers/quanlysach_controller.rb
class QuanlysachController < ApplicationController

    before_action :set_friend, only: %i[ show edit update destroy ]

    # GET /friends or /friends.json
    def index
      @friends = Friend.all
    end
  
    # GET /friends/1 or /friends/1.json
    def show
    end
  
    # GET /friends/new
    def new
      @friend = Friend.new
    end
  
    # GET /friends/1/edit
    def edit
    end
  
    # POST /friends or /friends.json
    def create
      @friend = Friend.new(friend_params)
  
      respond_to do |format|
        if @friend.save
          format.html { redirect_to friend_url(@friend), notice: "Friend was successfully created." }
          format.json { render :show, status: :created, location: @friend }
        else
          format.html { render :new, status: :unprocessable_entity }
          format.json { render json: @friend.errors, status: :unprocessable_entity }
        end
      end
    end
  
    # PATCH/PUT /friends/1 or /friends/1.json
    def update
      respond_to do |format|
        if @friend.update(friend_params)
          format.html { redirect_to friend_url(@friend), notice: "Friend was successfully updated." }
          format.json { render :show, status: :ok, location: @friend }
        else
          format.html { render :edit, status: :unprocessable_entity }
          format.json { render json: @friend.errors, status: :unprocessable_entity }
        end
      end
    end
  
    # DELETE /friends/1 or /friends/1.json
    def destroy
      @friend.destroy
  
      respond_to do |format|
        format.html { redirect_to friends_url, notice: "Friend was successfully destroyed." }
        format.json { head :no_content }
      end
    end
  
    private
      # Use callbacks to share common setup or constraints between actions.
      def set_friend
        @friend = Friend.find(params[:id])
      end
  
      # Only allow a list of trusted parameters through.
      def friend_params
        params.require(:friend).permit(:first_name, :last_name, :phone, :twiter)
      end
end

RuBy_on_rail/Tuan9/project_rails-ruby/app/helpers/application_helper.rb
module ApplicationHelper
end

RuBy_on_rail/Tuan9/project_rails-ruby/app/helpers/books_helper.rb
module BooksHelper
end

RuBy_on_rail/Tuan9/project_rails-ruby/app/helpers/friends_helper.rb
module FriendsHelper
end

RuBy_on_rail/Tuan9/project_rails-ruby/app/helpers/pages_helper.rb
module PagesHelper
end

RuBy_on_rail/Tuan9/project_rails-ruby/app/helpers/quanlysach_helper.rb
module QuanlysachHelper
end

RuBy_on_rail/Tuan9/project_rails-ruby/app/views/books/_book.html.erb
<div id="<%= dom_id book %>">
  <p>
    <strong>Mahs 236:</strong>
    <%= book.mahs_236 %>
  </p>

  <p>
    <strong>Hoten 236:</strong>
    <%= book.hoten_236 %>
  </p>

  <p>
    <strong>Lop 236:</strong>
    <%= book.lop_236 %>
  </p>

  <p>
    <strong>Manganh 236:</strong>
    <%= book.manganh_236 %>
  </p>

  <p>
    <strong>Tensach 236:</strong>
    <%= book.tensach_236 %>
  </p>

  <p>
    <strong>Tentacgia 236:</strong>
    <%= book.tentacgia_236 %>
  </p>

  <p>
    <strong>Sobm 236:</strong>
    <%= book.soBM_236 %>
  </p>

  <p>
    <strong>Ngaymuon 236:</strong>
    <%= book.ngaymuon_236 %>
  </p>

  <p>
    <strong>Ngaytra 236:</strong>
    <%= book.ngaytra_236 %>
  </p>

  <p>
    <strong>Ghichu 236:</strong>
    <%= book.ghichu_236 %>
  </p>

</div>

RuBy_on_rail/Tuan9/project_rails-ruby/app/views/books/_form.html.erb
<%= form_with(model: book) do |form| %>
  <% if book.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
        <% book.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :mahs_236,  class:"form-label" %>
    <%= form.text_field :mahs_236 , class:"form-control" %>

  </div>

  <div>
    <%= form.label :hoten_236, style: "display: block", class:"form-label" %>
    <%= form.text_field :hoten_236 ,class:"form-control" %>
  </div>

  <div>
    <%= form.label :lop_236, style: "display: block" %>
    <%= form.text_field :lop_236 ,class:"form-control" %>
  </div>

  <div>
    <%= form.label :manganh_236, style: "display: block" %>
    <%= form.text_field :manganh_236 ,class:"form-control" %>
  </div>

  <div>
    <%= form.label :tensach_236, style: "display: block" %>
    <%= form.text_field :tensach_236 ,class:"form-control" %>
  </div>

  <div>
    <%= form.label :tentacgia_236, style: "display: block" %>
    <%= form.text_field :tentacgia_236 ,class:"form-control" %>
  </div>

  <div>
    <%= form.label :soBM_236, style: "display: block" %>
    <%= form.text_field :soBM_236 ,class:"form-control" %>
  </div>

  <div>
    <%= form.label :ngaymuon_236, style: "display: block" %>
    <%= form.date_field :ngaymuon_236 ,class:"form-control" %>
  </div>

  <div>
    <%= form.label :ngaytra_236, style: "display: block" %>
    <%= form.date_field :ngaytra_236 ,class:"form-control" %>
  </div>

  <div>
    <%= form.label :ghichu_236, style: "display: block" %>
    <%= form.text_area :ghichu_236 ,class:"form-control" %>
  </div>

  <div >
    <%= form.submit %>
  </div>

<% end %>

RuBy_on_rail/Tuan9/project_rails-ruby/app/views/books/edit.html.erb
<h1>Editing book</h1>

<%= render "form", book: @book %>

<br>

<div>
  <%= link_to "Show this book", @book %> |
  <%= link_to "Back to books", books_path %>
</div>

RuBy_on_rail/Tuan9/project_rails-ruby/app/views/books/index.html.erb
<p style="color: green"><%= notice %></p>

<h1 class="text-center">Quản lý Mượn sách</h1>

<div id="books">

<table class="table table-striped">
  <thead>
    <tr class="table-primary">
      <th scope="col">#</th>
      <th scope="col">Mã Sinh viên</th>
      <th scope="col">Họ tên</th>
      <th scope="col">Lớp</th>
      <th scope="col">Ngành</th>
      <th scope="col">Tên sách</th>
      <th scope="col">Tên tác giã</th>
      <th scope="col">Mã BH</th>
      <th scope="col">Ngày mượn</th>
      <th scope="col">Ngay Trả</th>
      <th scope="col">Ghi chú</th>
    </tr>
  </thead>
  <tbody>
     <% @books.each do |book| %>
      <tr>
        <th scope="row">1</th>
        <td><%= book.mahs_236 %></td>
        <td><%= book.hoten_236 %></td>
        <td><%= book.lop_236 %></td>
        <td><%= book.manganh_236 %></td>
        <td><%= book.tensach_236 %></td>
        <td><%= book.tentacgia_236 %></td>
        <td><%= book.soBM_236 %></td>
        <td><%= book.ngaymuon_236 %></td>
        <td><%= book.ngaytra_236 %></td>
        <td><%= link_to "Show", book %></td>
      </tr>
    <% end %>
  </tbody>
</table>

</div>

<%= link_to "New book", new_book_path %>

RuBy_on_rail/Tuan9/project_rails-ruby/app/views/books/new.html.erb
<h1 class="text-center">Thêm mới Phiếu mượn</h1>

<%= render "form", book: @book %>

<br>

<div class="container">
  <%= link_to "Back to books", books_path %>
</div>

RuBy_on_rail/Tuan9/project_rails-ruby/app/views/books/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @book %>

<div>
  <%= link_to "Edit this book", edit_book_path(@book) %> |
  <%= link_to "Back to books", books_path %>

  <%= button_to "Destroy this book", @book, method: :delete %>
</div>

RuBy_on_rail/Tuan9/project_rails-ruby/app/views/friends/_form.html.erb
<%= form_with(model: friend) do |form| %>
  <% if friend.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(friend.errors.count, "error") %> prohibited this friend from being saved:</h2>

      <ul>
        <% friend.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :first_name, style: "display: block" %>
    <%= form.text_field :first_name %>
  </div>

  <div>
    <%= form.label :last_name, style: "display: block" %>
    <%= form.text_field :last_name %>
  </div>

  <div>
    <%= form.label :phone, style: "display: block" %>
    <%= form.text_field :phone %>
  </div>

  <div>
    <%= form.label :twiter, style: "display: block" %>
    <%= form.text_field :twiter %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

RuBy_on_rail/Tuan9/project_rails-ruby/app/views/friends/_friend.html.erb
<div id="<%= dom_id friend %>">
  <p>
    <strong>First name:</strong>
    <%= friend.first_name %>
  </p>

  <p>
    <strong>Last name:</strong>
    <%= friend.last_name %>
  </p>

  <p>
    <strong>Phone:</strong>
    <%= friend.phone %>
  </p>

  <p>
    <strong>Twiter: @</strong>
    <%= friend.twiter %>
  </p>
</div>

RuBy_on_rail/Tuan9/project_rails-ruby/app/views/friends/edit.html.erb
<h1>Editing friend</h1>

<%= render "form", friend: @friend %>

<br>

<div>
  <%= link_to "Show", @friend %> |
  <%= link_to "Back", friends_path %>
</div>

RuBy_on_rail/Tuan9/project_rails-ruby/app/views/friends/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Friends</h1>
<%= link_to "New friend", new_friend_path %>

<table class="table">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">First name</th>
      <th scope="col">Last name</th>
      <th scope="col">Phone</th>
      <th scope="col">twiter</th>
      <th scope="col"></th>
    </tr>
  </thead>
  <tbody>
    <% @friends.each do |friend| %>
      <tr>
        <th scope="row">1</th>
        <td><%= friend.first_name %></td>
        <td><%= friend.last_name %></td>
        <td><%= friend.phone %></td>
        <td>@<%= friend.twiter %></td>
        <td><%= link_to "Show", friend %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>

RuBy_on_rail/Tuan9/project_rails-ruby/app/views/friends/new.html.erb
<h1>New friend</h1>

<%= render "form", friend: @friend %>

<br>

<div>
  <%= link_to "Back to friends", friends_path %>
</div>

RuBy_on_rail/Tuan9/project_rails-ruby/app/views/friends/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @friend %>

<div>
  <%= link_to "Edit", edit_friend_path(@friend) %> |
  <%= link_to "Back", friends_path %>
  <%= button_to "Destroy", @friend, method: :delete %>
</div>

RuBy_on_rail/Tuan9/project_rails-ruby/app/views/layouts/_footer.html.erb
<footer class="bg-light text-dark">
      <div class="container" >
            <div class="row">
                  <div class="col">
                        <h3>MDN</h3>
                        <ul>
                              <li>About</li>
                              <li>Hacks Blog</li>
                              <li>Careers</li>
                        </ul>
                  </div>
                  <div class="col">
                        <h3>Support</h3>
                        <ul>
                              <li>About</li>
                              <li>Hacks Blog</li>
                              <li>Careers</li>
                        </ul>
                  </div>
                  <div class="col">
                        <h3>Our communities</h3>
                        <ul>
                              <li>About</li>
                              <li>Hacks Blog</li>
                              <li>Careers</li>
                        </ul>
                  </div>
                  <div class="col">
                        <h3>Developers</h3>
                        <ul>
                              <li>About</li>
                              <li>Hacks Blog</li>
                              <li>Careers</li>
                        </ul>
                  </div>
            </div>
      </div>
</footer>

RuBy_on_rail/Tuan9/project_rails-ruby/app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <%= link_to "My Blog", root_path, class:'navbar-brand' %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to "Home", root_path, class:'nav-link active' %>
        </li>
        <li class="nav-item">
          <%= link_to "About", about_path, class:'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to "Friends", friends_path, class:'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to "Books", books_path, class:'nav-link' %>
        </li>
      </ul>
      <ul class="navbar-nav">
         <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            User
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="#">Action</a></li>
            <li><a class="dropdown-item" href="#">Another action</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li>
      </ul>
    </div>
  </div>
</nav>

RuBy_on_rail/Tuan9/project_rails-ruby/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Project</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <%= render 'layouts/header' %>  
    <div class="container">
      <%= yield %>
    </div>
  </body>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
</html>

RuBy_on_rail/Tuan9/project_rails-ruby/app/views/quanlysach/_form.html.erb
<%= form_with(model: friend) do |form| %>
  <% if friend.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(friend.errors.count, "error") %> prohibited this friend from being saved:</h2>

      <ul>
        <% friend.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :first_name, style: "display: block" %>
    <%= form.text_field :first_name %>
  </div>

  <div>
    <%= form.label :last_name, style: "display: block" %>
    <%= form.text_field :last_name %>
  </div>

  <div>
    <%= form.label :phone, style: "display: block" %>
    <%= form.text_field :phone %>
  </div>

  <div>
    <%= form.label :twiter, style: "display: block" %>
    <%= form.text_field :twiter %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

RuBy_on_rail/Tuan9/project_rails-ruby/app/views/quanlysach/_quanly.html.erb
<div id="<%= dom_id friend %>">
  <p>
    <strong>First name:</strong>
    <%= friend.first_name %>
  </p>

  <p>
    <strong>Last name:</strong>
    <%= friend.last_name %>
  </p>

  <p>
    <strong>Phone:</strong>
    <%= friend.phone %>
  </p>

  <p>
    <strong>Twiter: @</strong>
    <%= friend.twiter %>
  </p>
</div>

RuBy_on_rail/Tuan9/project_rails-ruby/app/views/quanlysach/edit.html.erb
<h1>Editing friend</h1>

<%= render "form", friend: @friend %>

<br>

<div>
  <%= link_to "Show", @friend %> |
  <%= link_to "Back", friends_path %>
</div>

RuBy_on_rail/Tuan9/project_rails-ruby/app/views/quanlysach/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Friends</h1>
<%= link_to "New friend", new_friend_path %>

<table class="table">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">First name</th>
      <th scope="col">Last name</th>
      <th scope="col">Phone</th>
      <th scope="col">twiter</th>
      <th scope="col"></th>
    </tr>
  </thead>
  <tbody>
    <% @friends.each do |friend| %>
      <tr>
        <th scope="row">1</th>
        <td><%= friend.first_name %></td>
        <td><%= friend.last_name %></td>
        <td><%= friend.phone %></td>
        <td>@<%= friend.twiter %></td>
        <td><%= link_to "Show", friend %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>

RuBy_on_rail/Tuan9/project_rails-ruby/app/views/quanlysach/new.html.erb
<h1>New friend</h1>

<%= render "form", friend: @friend %>

<br>

<div>
  <%= link_to "Back to friends", friends_path %>
</div>

RuBy_on_rail/Tuan9/project_rails-ruby/app/views/quanlysach/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @friend %>

<div>
  <%= link_to "Edit", edit_friend_path(@friend) %> |
  <%= link_to "Back", friends_path %>
  <%= button_to "Destroy", @friend, method: :delete %>
</div>